server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    initialize: true
    maxActive: 3
    initialization-mode: always
    continue-on-error: true
    plataform: postgresql

  jpa:
    hibernate:
      ddl-auto: create-drop
      format-sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true

app-config:
  api-secret: ${API_SECRET:YXV0aC1hcGktbWljcm9zZXJ2aWNlcy1jb3Vyc2U=}
